package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "bigfish")
public class Application implements java.io.Serializable {

	private int applicationId;
	private String applicationName;

	public Application() {
	}

	public Application(int applicationId, String applicationName) {
		this.applicationId = applicationId;
		this.applicationName = applicationName;
	}

	@Id
	@Column(name = "applicationId", unique = true, nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "applicationName", nullable = false, length = 100)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

}
