package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "bigfish")
public class Attachment implements java.io.Serializable {

	private int attachmentId;
	private Date date;
	private String attachmentUrl;
	private String changeId;
	private String deployRequestId;
	private String serviceRequestId;

	public Attachment() {
	}

	public Attachment(int attachmentId, Date date, String attachmentUrl) {
		this.attachmentId = attachmentId;
		this.date = date;
		this.attachmentUrl = attachmentUrl;
	}

	public Attachment(int attachmentId, Date date, String attachmentUrl,
			String changeId, String deployRequestId, String serviceRequestId) {
		this.attachmentId = attachmentId;
		this.date = date;
		this.attachmentUrl = attachmentUrl;
		this.changeId = changeId;
		this.deployRequestId = deployRequestId;
		this.serviceRequestId = serviceRequestId;
	}

	@Id
	@Column(name = "attachmentId", unique = true, nullable = false)
	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "attachmentURL", nullable = false, length = 200)
	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	@Column(name = "changeId", length = 50)
	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

	@Column(name = "deployRequestId", length = 50)
	public String getDeployRequestId() {
		return this.deployRequestId;
	}

	public void setDeployRequestId(String deployRequestId) {
		this.deployRequestId = deployRequestId;
	}

	@Column(name = "serviceRequestId", length = 50)
	public String getServiceRequestId() {
		return this.serviceRequestId;
	}

	public void setServiceRequestId(String serviceRequestId) {
		this.serviceRequestId = serviceRequestId;
	}

}
