package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bigfishuser generated by hbm2java
 */
@Entity
@Table(name = "bigfishuser", catalog = "bigfish")
public class Bigfishuser implements java.io.Serializable {

	private int userId;
	private Userdepartment userdepartment;
	private String firstName;
	private String middleName;
	private String lastName;
	private String contactNo1;
	private String contactNo2;
	private String email;
	private String isActive;
	private String userName;
	private String password;
	private Set userroles = new HashSet(0);

	public Bigfishuser() {
	}

	public Bigfishuser(int userId, Userdepartment userdepartment,
			String firstName, String middleName, String lastName,
			String contactNo1, String email, String isActive, String userName,
			String password) {
		this.userId = userId;
		this.userdepartment = userdepartment;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.contactNo1 = contactNo1;
		this.email = email;
		this.isActive = isActive;
		this.userName = userName;
		this.password = password;
	}

	public Bigfishuser(int userId, Userdepartment userdepartment,
			String firstName, String middleName, String lastName,
			String contactNo1, String contactNo2, String email,
			String isActive, String userName, String password, Set userroles) {
		this.userId = userId;
		this.userdepartment = userdepartment;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.contactNo1 = contactNo1;
		this.contactNo2 = contactNo2;
		this.email = email;
		this.isActive = isActive;
		this.userName = userName;
		this.password = password;
		this.userroles = userroles;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departmentId", nullable = false)
	public Userdepartment getUserdepartment() {
		return this.userdepartment;
	}

	public void setUserdepartment(Userdepartment userdepartment) {
		this.userdepartment = userdepartment;
	}

	@Column(name = "FirstName", nullable = false, length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleName", nullable = false, length = 100)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LastName", nullable = false, length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "contactNo1", nullable = false, length = 10)
	public String getContactNo1() {
		return this.contactNo1;
	}

	public void setContactNo1(String contactNo1) {
		this.contactNo1 = contactNo1;
	}

	@Column(name = "contactNo2", length = 10)
	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "isActive", nullable = false, length = 1)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "userName", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bigfishuser")
	public Set<Userrole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<Userrole> userroles) {
		this.userroles = userroles;
	}

}
