package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bigfishdatabases generated by hbm2java
 */
@Entity
@Table(name = "bigfishdatabases", catalog = "bigfish")
public class Bigfishdatabases implements java.io.Serializable {

	private int bigFishDatabasesId;
	private String bigFishDatabasesName;

	public Bigfishdatabases() {
	}

	public Bigfishdatabases(int bigFishDatabasesId, String bigFishDatabasesName) {
		this.bigFishDatabasesId = bigFishDatabasesId;
		this.bigFishDatabasesName = bigFishDatabasesName;
	}

	@Id
	@Column(name = "BigFishDatabasesId", unique = true, nullable = false)
	public int getBigFishDatabasesId() {
		return this.bigFishDatabasesId;
	}

	public void setBigFishDatabasesId(int bigFishDatabasesId) {
		this.bigFishDatabasesId = bigFishDatabasesId;
	}

	@Column(name = "BigFishDatabasesName", nullable = false, length = 100)
	public String getBigFishDatabasesName() {
		return this.bigFishDatabasesName;
	}

	public void setBigFishDatabasesName(String bigFishDatabasesName) {
		this.bigFishDatabasesName = bigFishDatabasesName;
	}

}
