package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Changestatus generated by hbm2java
 */
@Entity
@Table(name = "changestatus", catalog = "bigfish")
public class Changestatus implements java.io.Serializable {

	private int changeStatusId;
	private String statusName;

	public Changestatus() {
	}

	public Changestatus(int changeStatusId, String statusName) {
		this.changeStatusId = changeStatusId;
		this.statusName = statusName;
	}

	@Id
	@Column(name = "changeStatusId", unique = true, nullable = false)
	public int getChangeStatusId() {
		return this.changeStatusId;
	}

	public void setChangeStatusId(int changeStatusId) {
		this.changeStatusId = changeStatusId;
	}

	@Column(name = "statusName", nullable = false, length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
