package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Changerequest generated by hbm2java
 */
@Entity
@Table(name = "changerequest", catalog = "bigfish")
public class Changerequest implements java.io.Serializable {

	private String changeId;
	private String title;
	private String description;
	private String assignedTo;
	private int estimatedHours;
	private Integer actualHours;
	private Date estimatedStDt;
	private Date estimatedEdDt;
	private Date dueDt;
	private Date updatedDt;
	private int updatedBy;
	private int applicationId;
	private Date assignedDt;
	private String status;
	private String complexity;

	public Changerequest() {
	}

	public Changerequest(String changeId, String title, String description,
			String assignedTo, int estimatedHours, Date estimatedStDt,
			Date estimatedEdDt, Date dueDt, Date updatedDt, int updatedBy,
			int applicationId, Date assignedDt, String status, String complexity) {
		this.changeId = changeId;
		this.title = title;
		this.description = description;
		this.assignedTo = assignedTo;
		this.estimatedHours = estimatedHours;
		this.estimatedStDt = estimatedStDt;
		this.estimatedEdDt = estimatedEdDt;
		this.dueDt = dueDt;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
		this.applicationId = applicationId;
		this.assignedDt = assignedDt;
		this.status = status;
		this.complexity = complexity;
	}

	public Changerequest(String changeId, String title, String description,
			String assignedTo, int estimatedHours, Integer actualHours,
			Date estimatedStDt, Date estimatedEdDt, Date dueDt, Date updatedDt,
			int updatedBy, int applicationId, Date assignedDt, String status,
			String complexity) {
		this.changeId = changeId;
		this.title = title;
		this.description = description;
		this.assignedTo = assignedTo;
		this.estimatedHours = estimatedHours;
		this.actualHours = actualHours;
		this.estimatedStDt = estimatedStDt;
		this.estimatedEdDt = estimatedEdDt;
		this.dueDt = dueDt;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
		this.applicationId = applicationId;
		this.assignedDt = assignedDt;
		this.status = status;
		this.complexity = complexity;
	}

	@Id
	@Column(name = "changeId", unique = true, nullable = false, length = 50)
	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "assignedTo", nullable = false, length = 50)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "estimatedHours", nullable = false)
	public int getEstimatedHours() {
		return this.estimatedHours;
	}

	public void setEstimatedHours(int estimatedHours) {
		this.estimatedHours = estimatedHours;
	}

	@Column(name = "actualHours")
	public Integer getActualHours() {
		return this.actualHours;
	}

	public void setActualHours(Integer actualHours) {
		this.actualHours = actualHours;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "estimatedStDt", nullable = false, length = 10)
	public Date getEstimatedStDt() {
		return this.estimatedStDt;
	}

	public void setEstimatedStDt(Date estimatedStDt) {
		this.estimatedStDt = estimatedStDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "estimatedEdDt", nullable = false, length = 10)
	public Date getEstimatedEdDt() {
		return this.estimatedEdDt;
	}

	public void setEstimatedEdDt(Date estimatedEdDt) {
		this.estimatedEdDt = estimatedEdDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dueDt", nullable = false, length = 10)
	public Date getDueDt() {
		return this.dueDt;
	}

	public void setDueDt(Date dueDt) {
		this.dueDt = dueDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatedDt", nullable = false, length = 10)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "updatedBy", nullable = false)
	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "applicationId", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assignedDt", nullable = false, length = 10)
	public Date getAssignedDt() {
		return this.assignedDt;
	}

	public void setAssignedDt(Date assignedDt) {
		this.assignedDt = assignedDt;
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "complexity", nullable = false, length = 50)
	public String getComplexity() {
		return this.complexity;
	}

	public void setComplexity(String complexity) {
		this.complexity = complexity;
	}

}
