package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Defectseverity generated by hbm2java
 */
@Entity
@Table(name = "defectseverity", catalog = "bigfish")
public class Defectseverity implements java.io.Serializable {

	private int defectSeverityId;
	private String name;

	public Defectseverity() {
	}

	public Defectseverity(int defectSeverityId, String name) {
		this.defectSeverityId = defectSeverityId;
		this.name = name;
	}

	@Id
	@Column(name = "DefectSeverityId", unique = true, nullable = false)
	public int getDefectSeverityId() {
		return this.defectSeverityId;
	}

	public void setDefectSeverityId(int defectSeverityId) {
		this.defectSeverityId = defectSeverityId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
