package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Defectcause generated by hbm2java
 */
@Entity
@Table(name = "defectcause", catalog = "bigfish")
public class Defectcause implements java.io.Serializable {

	private int defectCausedId;
	private String name;

	public Defectcause() {
	}

	public Defectcause(int defectCausedId, String name) {
		this.defectCausedId = defectCausedId;
		this.name = name;
	}

	@Id
	@Column(name = "defectCausedId", unique = true, nullable = false)
	public int getDefectCausedId() {
		return this.defectCausedId;
	}

	public void setDefectCausedId(int defectCausedId) {
		this.defectCausedId = defectCausedId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
