package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Defecttype generated by hbm2java
 */
@Entity
@Table(name = "defecttype", catalog = "bigfish")
public class Defecttype implements java.io.Serializable {

	private int defectTypeId;
	private String typeName;

	public Defecttype() {
	}

	public Defecttype(int defectTypeId, String typeName) {
		this.defectTypeId = defectTypeId;
		this.typeName = typeName;
	}

	@Id
	@Column(name = "defectTypeId", unique = true, nullable = false)
	public int getDefectTypeId() {
		return this.defectTypeId;
	}

	public void setDefectTypeId(int defectTypeId) {
		this.defectTypeId = defectTypeId;
	}

	@Column(name = "typeName", nullable = false, length = 100)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
