package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deployitemlist generated by hbm2java
 */
@Entity
@Table(name = "deployitemlist", catalog = "bigfish")
public class Deployitemlist implements java.io.Serializable {

	private int deployItemListId;
	private String deployRequestId;
	private String serviceRequestId;
	private String changeId;
	private Date updatedDt;
	private int updatedBy;

	public Deployitemlist() {
	}

	public Deployitemlist(int deployItemListId, String deployRequestId,
			String serviceRequestId, String changeId, Date updatedDt,
			int updatedBy) {
		this.deployItemListId = deployItemListId;
		this.deployRequestId = deployRequestId;
		this.serviceRequestId = serviceRequestId;
		this.changeId = changeId;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "deployItemListId", unique = true, nullable = false)
	public int getDeployItemListId() {
		return this.deployItemListId;
	}

	public void setDeployItemListId(int deployItemListId) {
		this.deployItemListId = deployItemListId;
	}

	@Column(name = "deployRequestId", nullable = false, length = 50)
	public String getDeployRequestId() {
		return this.deployRequestId;
	}

	public void setDeployRequestId(String deployRequestId) {
		this.deployRequestId = deployRequestId;
	}

	@Column(name = "serviceRequestId", nullable = false, length = 50)
	public String getServiceRequestId() {
		return this.serviceRequestId;
	}

	public void setServiceRequestId(String serviceRequestId) {
		this.serviceRequestId = serviceRequestId;
	}

	@Column(name = "changeId", nullable = false, length = 50)
	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatedDt", nullable = false, length = 10)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "updatedBy", nullable = false)
	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

}
