package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Deployitemtype generated by hbm2java
 */
@Entity
@Table(name = "deployitemtype", catalog = "bigfish")
public class Deployitemtype implements java.io.Serializable {

	private int deployItemTypId;
	private String itemName;

	public Deployitemtype() {
	}

	public Deployitemtype(int deployItemTypId, String itemName) {
		this.deployItemTypId = deployItemTypId;
		this.itemName = itemName;
	}

	@Id
	@Column(name = "deployItemTypId", unique = true, nullable = false)
	public int getDeployItemTypId() {
		return this.deployItemTypId;
	}

	public void setDeployItemTypId(int deployItemTypId) {
		this.deployItemTypId = deployItemTypId;
	}

	@Column(name = "itemName", nullable = false, length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

}
