package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeployrequestitemmapId generated by hbm2java
 */
@Embeddable
public class DeployrequestitemmapId implements java.io.Serializable {

	private int deployItemTypId;
	private String deployRequestId;

	public DeployrequestitemmapId() {
	}

	public DeployrequestitemmapId(int deployItemTypId, String deployRequestId) {
		this.deployItemTypId = deployItemTypId;
		this.deployRequestId = deployRequestId;
	}

	@Column(name = "deployItemTypId", nullable = false)
	public int getDeployItemTypId() {
		return this.deployItemTypId;
	}

	public void setDeployItemTypId(int deployItemTypId) {
		this.deployItemTypId = deployItemTypId;
	}

	@Column(name = "deployRequestId", nullable = false, length = 50)
	public String getDeployRequestId() {
		return this.deployRequestId;
	}

	public void setDeployRequestId(String deployRequestId) {
		this.deployRequestId = deployRequestId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeployrequestitemmapId))
			return false;
		DeployrequestitemmapId castOther = (DeployrequestitemmapId) other;

		return (this.getDeployItemTypId() == castOther.getDeployItemTypId())
				&& ((this.getDeployRequestId() == castOther
						.getDeployRequestId()) || (this.getDeployRequestId() != null
						&& castOther.getDeployRequestId() != null && this
						.getDeployRequestId().equals(
								castOther.getDeployRequestId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDeployItemTypId();
		result = 37
				* result
				+ (getDeployRequestId() == null ? 0 : this.getDeployRequestId()
						.hashCode());
		return result;
	}

}
