package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deployrequest generated by hbm2java
 */
@Entity
@Table(name = "deployrequest", catalog = "bigfish")
public class Deployrequest implements java.io.Serializable {

	private String deployRequestId;
	private String assignedTo;
	private Date assignedDt;
	private Date deployDt;
	private String businessDescription;
	private String deployInstructions;
	private String rollbackInstruction;
	private int applicationId;
	private int bigFishDatabasesId;
	private int deployStageId;
	private int deployTypeId;
	private Date updatedDt;
	private int updatedBy;

	public Deployrequest() {
	}

	public Deployrequest(String deployRequestId, String assignedTo,
			Date assignedDt, Date deployDt, String businessDescription,
			String deployInstructions, String rollbackInstruction,
			int applicationId, int bigFishDatabasesId, int deployStageId,
			int deployTypeId, Date updatedDt, int updatedBy) {
		this.deployRequestId = deployRequestId;
		this.assignedTo = assignedTo;
		this.assignedDt = assignedDt;
		this.deployDt = deployDt;
		this.businessDescription = businessDescription;
		this.deployInstructions = deployInstructions;
		this.rollbackInstruction = rollbackInstruction;
		this.applicationId = applicationId;
		this.bigFishDatabasesId = bigFishDatabasesId;
		this.deployStageId = deployStageId;
		this.deployTypeId = deployTypeId;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "deployRequestId", unique = true, nullable = false, length = 50)
	public String getDeployRequestId() {
		return this.deployRequestId;
	}

	public void setDeployRequestId(String deployRequestId) {
		this.deployRequestId = deployRequestId;
	}

	@Column(name = "assignedTo", nullable = false, length = 50)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assignedDt", nullable = false, length = 10)
	public Date getAssignedDt() {
		return this.assignedDt;
	}

	public void setAssignedDt(Date assignedDt) {
		this.assignedDt = assignedDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deployDt", nullable = false, length = 10)
	public Date getDeployDt() {
		return this.deployDt;
	}

	public void setDeployDt(Date deployDt) {
		this.deployDt = deployDt;
	}

	@Column(name = "businessDescription", nullable = false, length = 65535)
	public String getBusinessDescription() {
		return this.businessDescription;
	}

	public void setBusinessDescription(String businessDescription) {
		this.businessDescription = businessDescription;
	}

	@Column(name = "deployInstructions", nullable = false, length = 65535)
	public String getDeployInstructions() {
		return this.deployInstructions;
	}

	public void setDeployInstructions(String deployInstructions) {
		this.deployInstructions = deployInstructions;
	}

	@Column(name = "rollbackInstruction", nullable = false, length = 65535)
	public String getRollbackInstruction() {
		return this.rollbackInstruction;
	}

	public void setRollbackInstruction(String rollbackInstruction) {
		this.rollbackInstruction = rollbackInstruction;
	}

	@Column(name = "applicationId", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "BigFishDatabasesId", nullable = false)
	public int getBigFishDatabasesId() {
		return this.bigFishDatabasesId;
	}

	public void setBigFishDatabasesId(int bigFishDatabasesId) {
		this.bigFishDatabasesId = bigFishDatabasesId;
	}

	@Column(name = "deployStageId", nullable = false)
	public int getDeployStageId() {
		return this.deployStageId;
	}

	public void setDeployStageId(int deployStageId) {
		this.deployStageId = deployStageId;
	}

	@Column(name = "deployTypeId", nullable = false)
	public int getDeployTypeId() {
		return this.deployTypeId;
	}

	public void setDeployTypeId(int deployTypeId) {
		this.deployTypeId = deployTypeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatedDt", nullable = false, length = 10)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "updatedBy", nullable = false)
	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

}
