package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicetype generated by hbm2java
 */
@Entity
@Table(name = "servicetype", catalog = "bigfish")
public class Servicetype implements java.io.Serializable {

	private int serviceTypeId;
	private String serviceName;

	public Servicetype() {
	}

	public Servicetype(int serviceTypeId, String serviceName) {
		this.serviceTypeId = serviceTypeId;
		this.serviceName = serviceName;
	}

	@Id
	@Column(name = "serviceTypeId", unique = true, nullable = false)
	public int getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(int serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "serviceName", nullable = false, length = 100)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

}
