package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicerequest generated by hbm2java
 */
@Entity
@Table(name = "servicerequest", catalog = "bigfish")
public class Servicerequest implements java.io.Serializable {

	private String serviceRequestId;
	private String title;
	private String description;
	private String assignedTo;
	private Date assignedDt;
	private Date estimatedStDt;
	private Date estimatedEdDt;
	private Integer taskStatusId;
	private Integer serviceTypeId;
	private Date dueDt;
	private Date updatedDt;
	private int updatedBy;
	private int applicationId;
	private String changeId;

	public Servicerequest() {
	}

	public Servicerequest(String serviceRequestId, String title,
			String description, String assignedTo, Date assignedDt,
			Date estimatedStDt, Date estimatedEdDt, Date dueDt, Date updatedDt,
			int updatedBy, int applicationId) {
		this.serviceRequestId = serviceRequestId;
		this.title = title;
		this.description = description;
		this.assignedTo = assignedTo;
		this.assignedDt = assignedDt;
		this.estimatedStDt = estimatedStDt;
		this.estimatedEdDt = estimatedEdDt;
		this.dueDt = dueDt;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
		this.applicationId = applicationId;
	}

	public Servicerequest(String serviceRequestId, String title,
			String description, String assignedTo, Date assignedDt,
			Date estimatedStDt, Date estimatedEdDt, Integer taskStatusId,
			Integer serviceTypeId, Date dueDt, Date updatedDt, int updatedBy,
			int applicationId, String changeId) {
		this.serviceRequestId = serviceRequestId;
		this.title = title;
		this.description = description;
		this.assignedTo = assignedTo;
		this.assignedDt = assignedDt;
		this.estimatedStDt = estimatedStDt;
		this.estimatedEdDt = estimatedEdDt;
		this.taskStatusId = taskStatusId;
		this.serviceTypeId = serviceTypeId;
		this.dueDt = dueDt;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
		this.applicationId = applicationId;
		this.changeId = changeId;
	}

	@Id
	@Column(name = "serviceRequestId", unique = true, nullable = false, length = 50)
	public String getServiceRequestId() {
		return this.serviceRequestId;
	}

	public void setServiceRequestId(String serviceRequestId) {
		this.serviceRequestId = serviceRequestId;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "assignedTo", nullable = false, length = 50)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assignedDt", nullable = false, length = 10)
	public Date getAssignedDt() {
		return this.assignedDt;
	}

	public void setAssignedDt(Date assignedDt) {
		this.assignedDt = assignedDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "estimatedStDt", nullable = false, length = 10)
	public Date getEstimatedStDt() {
		return this.estimatedStDt;
	}

	public void setEstimatedStDt(Date estimatedStDt) {
		this.estimatedStDt = estimatedStDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "estimatedEdDt", nullable = false, length = 10)
	public Date getEstimatedEdDt() {
		return this.estimatedEdDt;
	}

	public void setEstimatedEdDt(Date estimatedEdDt) {
		this.estimatedEdDt = estimatedEdDt;
	}

	@Column(name = "taskStatusId")
	public Integer getTaskStatusId() {
		return this.taskStatusId;
	}

	public void setTaskStatusId(Integer taskStatusId) {
		this.taskStatusId = taskStatusId;
	}

	@Column(name = "serviceTypeId")
	public Integer getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(Integer serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dueDt", nullable = false, length = 10)
	public Date getDueDt() {
		return this.dueDt;
	}

	public void setDueDt(Date dueDt) {
		this.dueDt = dueDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatedDt", nullable = false, length = 10)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "updatedBy", nullable = false)
	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "applicationId", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "changeId", length = 50)
	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

}
