package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tasktype generated by hbm2java
 */
@Entity
@Table(name = "tasktype", catalog = "bigfish")
public class Tasktype implements java.io.Serializable {

	private int taskTypeId;
	private String taskName;

	public Tasktype() {
	}

	public Tasktype(int taskTypeId, String taskName) {
		this.taskTypeId = taskTypeId;
		this.taskName = taskName;
	}

	@Id
	@Column(name = "taskTypeId", unique = true, nullable = false)
	public int getTaskTypeId() {
		return this.taskTypeId;
	}

	public void setTaskTypeId(int taskTypeId) {
		this.taskTypeId = taskTypeId;
	}

	@Column(name = "taskName", nullable = false, length = 100)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

}
