package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usercomments generated by hbm2java
 */
@Entity
@Table(name = "usercomments", catalog = "bigfish")
public class Usercomments implements java.io.Serializable {

	private int commentId;
	private String description;
	private Date commentDt;
	private String changeId;
	private String deployRequestId;
	private String serviceRequestId;
	private Integer defectId;

	public Usercomments() {
	}

	public Usercomments(int commentId, String description, Date commentDt,
			String changeId, String deployRequestId, String serviceRequestId) {
		this.commentId = commentId;
		this.description = description;
		this.commentDt = commentDt;
		this.changeId = changeId;
		this.deployRequestId = deployRequestId;
		this.serviceRequestId = serviceRequestId;
	}

	public Usercomments(int commentId, String description, Date commentDt,
			String changeId, String deployRequestId, String serviceRequestId,
			Integer defectId) {
		this.commentId = commentId;
		this.description = description;
		this.commentDt = commentDt;
		this.changeId = changeId;
		this.deployRequestId = deployRequestId;
		this.serviceRequestId = serviceRequestId;
		this.defectId = defectId;
	}

	@Id
	@Column(name = "commentId", unique = true, nullable = false)
	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	@Column(name = "description", nullable = false, length = 3000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "commentDt", nullable = false, length = 10)
	public Date getCommentDt() {
		return this.commentDt;
	}

	public void setCommentDt(Date commentDt) {
		this.commentDt = commentDt;
	}

	@Column(name = "changeId", nullable = false, length = 50)
	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

	@Column(name = "deployRequestId", nullable = false, length = 50)
	public String getDeployRequestId() {
		return this.deployRequestId;
	}

	public void setDeployRequestId(String deployRequestId) {
		this.deployRequestId = deployRequestId;
	}

	@Column(name = "serviceRequestId", nullable = false, length = 50)
	public String getServiceRequestId() {
		return this.serviceRequestId;
	}

	public void setServiceRequestId(String serviceRequestId) {
		this.serviceRequestId = serviceRequestId;
	}

	@Column(name = "defectId")
	public Integer getDefectId() {
		return this.defectId;
	}

	public void setDefectId(Integer defectId) {
		this.defectId = defectId;
	}

}
