package com.tcs.bigfish.hibernate;

// Generated 24/10/2013 2:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Userdepartment generated by hbm2java
 */
@Entity
@Table(name = "userdepartment", catalog = "bigfish")
public class Userdepartment implements java.io.Serializable {

	private int departmentId;
	private String name;
	private String email;
	private Set bigfishusers = new HashSet(0);

	public Userdepartment() {
	}

	public Userdepartment(int departmentId, String name, String email) {
		this.departmentId = departmentId;
		this.name = name;
		this.email = email;
	}

	public Userdepartment(int departmentId, String name, String email,
			Set bigfishusers) {
		this.departmentId = departmentId;
		this.name = name;
		this.email = email;
		this.bigfishusers = bigfishusers;
	}

	@Id
	@Column(name = "departmentId", unique = true, nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userdepartment")
	public Set<Bigfishuser> getBigfishusers() {
		return this.bigfishusers;
	}

	public void setBigfishusers(Set<Bigfishuser> bigfishusers) {
		this.bigfishusers = bigfishusers;
	}

}
